default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: post_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: post_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: post_production
  username: post
  password: <%= ENV["POST_DATABASE_PASSWORD"] %>
